(function(){
  const S=window.SPOILAGE,root=document.getElementById('app');let uiSort='cost',endTimer=null,seenLog='';
  const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const artPos=(index,cols,rows)=>{const x=(index%cols)*(100/(cols-1)),y=Math.floor(index/cols)*(100/(rows-1));return `background-position:${x}% ${y}%`};
  const icon={combat:'⚔',elite:'♛',event:'⌘',market:'◈',kitchen:'✦',camp:'♨',boss:'♚'};
  const audio={ctx:null,gain:null,timer:null,ensure(){if(this.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.gain=this.ctx.createGain();this.gain.gain.value=game.settings.volume*.12;this.gain.connect(this.ctx.destination);this.timer=setInterval(()=>{if(!this.ctx||game.settings.volume<=0||document.hidden)return;const notes=[110,146.8,164.8,220];this.tone(notes[Math.floor(Math.random()*notes.length)],.75,.035,'triangle');},2600);},tone(freq,dur=.12,vol=.08,type='sine'){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+dur);o.connect(g);g.connect(this.gain);o.start();o.stop(this.ctx.currentTime+dur);},cue(kind){this.ensure();const map={play:[220,.08,'triangle'],damage:[90,.18,'sawtooth'],enemy:[75,.22,'square'],guard:[330,.11,'sine'],ripe:[440,.32,'sine'],perish:[130,.45,'triangle'],preserve:[520,.26,'sine'],rot:[105,.3,'triangle'],relic:[660,.35,'sine'],heal:[392,.24,'sine']};const m=map[kind];if(m)this.tone(m[0],m[1],.09,m[2]);},volume(){if(this.gain)this.gain.gain.value=game.settings.volume*.12;}};
  const game=new S.Game(render);

  function topbar(title,subtitle=''){
    const r=game.state.run;return `<div class="topbar"><div><div class="eyeline">${esc(subtitle||'The Orchard Verge')}</div><h1>${esc(title)}</h1></div>${r?`<div class="status-line"><span class="hp">♥ ${r.hp}/${r.maxHp}</span><span class="coin">● ${r.coin} Coin</span><span>Seed ${r.seed}</span></div>`:''}<div class="top-actions">${r?'<button class="btn ghost" data-action="deck">Deck</button>':''}<button class="btn ghost" data-action="settings">Settings</button>${r?'<button class="btn ghost" data-action="menu">Main menu</button>':''}</div></div>`;
  }
  function menu(){return `<main class="screen menu"><section class="menu-card"><h1 class="brand">Spoilage</h1><p class="tagline">Build a deck that is always dying—and learn to make its death useful.</p><div class="menu-buttons"><button class="btn primary" data-action="new">New run</button>${game.hasSave()?'<button class="btn" data-action="continue">Continue exact run</button>':''}<button class="btn" data-action="tutorial">Playable prologue</button><button class="btn" data-action="how">How to play</button><button class="btn" data-action="settings">Settings</button></div><div class="seed-row"><input id="seed-input" aria-label="Run seed" placeholder="Optional numeric or text seed"><button class="btn" data-action="new-seed">Start seeded</button></div><div class="version">v1.0 · The Provisioner</div></section></main>`;}
  function relicHTML(id){const r=S.relicById[id];return `<div class="relic ${game.flashRelic===id?'glow':''}" style="${artPos(r.art,5,4)}" title="${esc(r.name)} — ${esc(r.text)}" aria-label="${esc(r.name)}"></div>`;}
  function pile(label,count,klass=''){return `<div class="pile ${klass}"><b>${count}</b><span>${label}</span></div>`;}
  function cardState(card){if(card.freshness==null)return 'Stable';if(willPerish(card))return 'Perishing';return game.isRipe(card)?'Ripe':'Fresh';}
  function willPerish(card){const c=game.state.combat;return !!c&&card.freshness!=null&&card.freshness===1&&card.drawnTurn<c.turn&&!card.sealed;}
  function cardHTML(card,action='card'){
    const def=game.cardDef(card),state=cardState(card),c=game.state.combat,cost=c?game.cardCost(card):def.cost,old=c?game.oldestCard():null,targetable=!!c?.pendingPlay&&c.pendingPlay.uid!==card.uid;
    const classes=['card',state.toLowerCase(),def.shelf==null?'stable':'',old?.uid===card.uid?'oldest':'',willPerish(card)?'will-perish':'',c&&cost>c.vigor?'disabled':'',targetable?'targetable':''].filter(Boolean).join(' ');
    const pips=card.maxFreshness==null?'':Array.from({length:card.maxFreshness},(_,i)=>`<i class="pip ${i<card.freshness?'full':''}"></i>`).join('');
    return `<button class="${classes}" data-action="${action}" data-id="${card.uid}" aria-label="${esc(def.name)}. ${esc(state)}. ${esc(def.text)}"><span class="card-cost">${cost}</span>${card.upgraded?'<span class="upgrade-mark">+</span>':''}<strong class="card-name">${esc(def.name)}</strong><span class="card-art" style="${artPos(def.art||0,5,4)}"></span><span class="card-text">${esc(def.text)}</span><span class="card-type">${esc(def.type)}</span><span class="state-label">${state}${card.sealed?' · Sealed':''}</span><span class="pips">${pips}</span>${card.tempPower?`<span class="temp-power">+${card.tempPower} power</span>`:''}</button>`;
  }
  function enemyHTML(e,index){const d=S.enemyById[e.id],intent=game.nextIntent(e),pct=Math.max(0,e.hp/e.maxHp*100),st=[];if(e.status.tender)st.push(`Tender ${e.status.tender}`);if(e.markedUid)st.push('Target marked');return `<button class="enemy ${e.dead?'dead':''} ${game.state.combat.selectedEnemy===index?'selected':''}" data-action="enemy" data-id="${index}" aria-label="Target ${esc(d.name)}"><div class="intent"><strong>${index+1}</strong> ${esc(intent.label)}${d.boss?`<small> · ${esc(intent.phase)}</small>`:''}</div><div class="enemy-art" style="${artPos(d.art,5,2)}"></div><div class="enemy-name">${esc(d.name)}<div class="enemy-role">${esc(d.role)}</div></div><div class="bar"><i style="width:${pct}%"></i></div><div class="enemy-hp">${e.hp} / ${e.maxHp}${e.block?` · ${e.block} Guard`:''}</div><div class="enemy-statuses">${st.join(' · ')}</div></button>`;}
  function combat(){const c=game.state.combat,r=game.state.run;if(!c)return '';const pending=c.hand.filter(willPerish),rot=pending.reduce((n,x)=>{const p=game.cardDef(x).perish?.find(a=>a[0]==='rot');return n+(p?p[1]:1)},0);const targetMsg=c.pendingPlay?`Choose another card for ${esc(game.cardDef(c.hand.find(x=>x.uid===c.pendingPlay.uid)).name)} · <button class="btn ghost" data-action="cancel">Cancel</button>`:'';const boss=c.enemies.find(e=>S.enemyById[e.id].boss);
    const html=`<main class="screen combat"><aside class="hud-rail"><div class="combat-logo">Spoilage</div><section class="provisioner"><h2>The Provisioner</h2><div class="vital"><i>♥</i><span><strong>${r.hp}</strong><small> / ${r.maxHp} HP</small></span></div><div class="vital"><i>❧</i><span><strong>${c.vigor}</strong><small> Vigor</small></span></div><div class="vital"><i>◈</i><span><strong>${c.guard}</strong><small> Guard</small></span></div><div class="vital"><i>●</i><span><strong>${r.coin}</strong><small> Coin</small></span></div></section><div class="relics-title">Relics</div><div class="relic-strip">${r.relics.map(relicHTML).join('')}</div><div class="piles">${pile('Draw',c.draw.length)}${pile('Discard',c.discard.length)}${pile('Rot',c.rot,'rot')}${pile('Exhaust',c.exhaust.length,'exhaust')}</div><div class="hud-actions"><button class="btn" data-action="deck">Deck</button><button class="btn" data-action="settings">Settings</button><button class="btn" data-action="debug">Debug</button></div></aside><section class="combat-stage">${boss?`<div class="boss-phase">The Orchard King · <b>${esc(game.nextIntent(boss).phase)}</b><small>Next: ${esc(S.enemyById[boss.id].pattern[(boss.intentIndex+1)%3].phase)}</small></div>`:''}<div class="enemy-stage">${c.enemies.map(enemyHTML).join('')}</div><div class="hand-zone">${targetMsg?`<div class="target-callout">${targetMsg}</div>`:''}<div class="hand">${c.hand.map(x=>cardHTML(x)).join('')}</div><div class="turn-tray"><div class="end-preview ${pending.length?'danger':''}">${pending.length?`${pending.length} card${pending.length>1?'s':''} will perish → ${rot} Rot`:'No cards will perish'}<br><small>Turn ${c.turn} · Mold ${c.status.mold} · Sated ${c.status.sated} · Compost ${c.compost}</small></div><button class="end-turn ${pending.length?'danger':''}" data-action="end"><span class="hold-fill"></span>${game.settings.holdConfirm&&pending.length?'Hold to end':'End turn'}</button></div></div></section><aside class="log-rail"><div class="log-title">Combat log</div><div class="combat-log">${c.log.map(x=>`<div class="log-entry ${x.kind}"><small>T${x.turn}</small>${esc(x.text)}</div>`).join('')}</div><div class="log-footer"><button class="btn" data-action="how">Rules</button><button class="btn" data-action="menu">Save & menu</button></div></aside></main>`;
    return html+(r.tutorial?`<div class="tutorial-tip"><b>Prologue ${Math.min(r.tutorialStep+1,6)}/6</b><br>${esc(game.tutorialTip())}</div>`:'');}
  function map(){const r=game.state.run;return `<main class="screen paper-screen"><section class="paper-panel">${topbar('Orchard Verge','Route ledger')}<p class="route-note">Choose one node in the current row. Three rows ahead are disclosed; later ink remains wet.</p><div class="map-board">${r.map.map((row,ri)=>`<div class="map-row">${row.map((n,ni)=>{const visited=r.visited.some(v=>v.row===ri&&v.index===ni),future=ri>r.row+3;return `<button class="map-node ${ri===r.row?'active':''} ${visited?'visited':''} ${future?'hidden-node':''}" data-action="node" data-id="${ni}" ${ri!==r.row?'disabled':''}><span class="node-icon">${icon[n.type]}</span><span class="node-type">${esc(n.type)}</span><span class="node-label">${esc(n.label)}</span></button>`}).join('')}</div>`).join('')}</div></section></main>`;}
  function reward(){const r=game.state.run;return `<main class="screen paper-screen"><section class="paper-panel">${topbar('Choose a supply','Combat reward')}<p>Draft one of three cards, take Coin, or skip. Your deck currently holds ${r.deck.length} cards.</p><div class="choice-grid">${game.state.reward.map(id=>{const d=S.cardById[id],x={uid:id,id,upgraded:false,freshness:d.shelf,maxFreshness:d.shelf};return `<div class="reward-card">${cardHTML(x,'reward')}</div>`}).join('')}</div><div class="service-actions"><button class="btn" data-action="reward-coin">Take 15 Coin</button><button class="btn ghost" data-action="reward-skip">Skip</button></div></section></main>`;}
  function deckRows(selectAction){let list=game.state.run.deck.slice();list.sort((a,b)=>{const A=S.cardById[a.id],B=S.cardById[b.id];if(uiSort==='cost')return A.cost-B.cost||A.name.localeCompare(B.name);if(uiSort==='shelf')return (A.shelf??99)-(B.shelf??99);if(uiSort==='type')return A.type.localeCompare(B.type);return A.name.localeCompare(B.name)});return list.map(x=>{const d=game.cardDef(x);return `<button class="deck-row ${x.upgraded?'upgraded':''}" data-action="${selectAction}" data-id="${x.uid}"><strong>${esc(d.name)}</strong><small>${d.cost} Vigor · ${d.shelf==null?'Stable':`Life ${d.shelf+(x.shelfBonus||0)}`} · ${esc(d.type)}</small><small>${esc(d.text)}</small></button>`}).join('');}
  function kitchen(){return `<main class="screen paper-screen"><section class="paper-panel">${topbar('The Field Kitchen','Upgrade one card')}<p>One careful cut, one layer of wax, one better sentence in the ledger. Choose a card for its single-tier upgrade.</p><div class="deck-list">${deckRows('upgrade')}</div></section></main>`;}
  function camp(){const heal=Math.ceil(game.state.run.maxHp*.2);return `<main class="screen paper-screen"><section class="paper-panel">${topbar('Canvas Camp','Rest beneath the pear rows')}<p>The kettle is clean enough. The night is not.</p><div class="service-actions"><button class="choice" data-action="camp-heal"><h3>Rest</h3>Heal ${heal} HP.</button><button class="choice" data-action="camp-upgrade"><h3>Sharpen</h3>Upgrade one card.</button></div></section></main>`;}
  function market(){const m=game.state.market,r=game.state.run,removeCost=75+r.removals*25;return `<main class="screen paper-screen"><section class="paper-panel">${topbar('The Hedge Market','Everything priced before it turns')}<section class="market-section"><h2>Cards</h2><div class="market-items">${m.cards.map(id=>{const d=S.cardById[id],cost=d.rarity==='rare'?75:d.rarity==='uncommon'?55:38;return `<article class="market-item"><h3>${esc(d.name)}</h3><p>${esc(d.text)}</p><div class="price">${cost} Coin</div><button class="btn" data-action="buy-card" data-id="${id}">Buy</button></article>`}).join('')||'<p class="muted">The card shelf is bare.</p>'}</div></section><section class="market-section"><h2>Relics</h2><div class="market-items">${m.relics.map(id=>{const x=S.relicById[id];return `<article class="market-item relic-card"><div class="relic-large" style="${artPos(x.art,5,4)}"></div><div><h3>${esc(x.name)}</h3><p>${esc(x.text)}</p><div class="price">95 Coin</div><button class="btn" data-action="buy-relic" data-id="${id}">Buy</button></div></article>`}).join('')||'<p class="muted">No relics remain.</p>'}</div></section><section class="market-section"><h2>Removal · ${removeCost} Coin</h2><p>Expensive by local custom. Choose carefully.</p><div class="deck-list">${deckRows('remove')}</div></section><button class="btn primary" data-action="leave-market">Leave market</button></section></main>`;}
  function event(){const e=S.eventById[game.state.currentEvent];return `<main class="screen paper-screen"><section class="paper-panel">${topbar(e.name,'Field encounter')}<p class="event-copy">${esc(e.body)}</p><div class="choice-grid">${e.choices.map((c,i)=>`<button class="choice" data-action="event-choice" data-id="${i}"><h3>${esc(c.label)}</h3><span class="risk">${esc(c.risk)}</span></button>`).join('')}</div></section></main>`;}
  function tutorialReward(){return `<main class="screen paper-screen"><section class="paper-panel">${topbar('One last choice','Prologue · beat 6 of 6')}<p class="event-copy">The wasp is quiet. Two useful things remain on the worktable; usefulness is only another kind of deadline.</p><div class="choice-grid"><button class="choice" data-action="tutorial-finish" data-id="folded_leaf"><h3>Take Folded Leaf</h3><span class="risk">Preservation — protect timing-sensitive cards.</span></button><button class="choice" data-action="tutorial-finish" data-id="red_knife"><h3>Take Red Knife</h3><span class="risk">Tempo — spend value before it turns.</span></button></div></section></main>`;}
  function runEnd(win){const r=game.state.run,s=r.stats;return `<main class="screen paper-screen"><section class="paper-panel run-end"><div class="eyeline">${win?'The Last Cold House':'The road keeps its accounts'}</div><h1>${win?'Delivered':'Spoiled'}</h1><p class="epilogue">${esc(win?r.epilogue:'The orchard takes back what it lent. The next ledger begins with a clean page.')}</p><div class="stat-grid">${[['Cards played',s.cardsPlayed],['Cards perished',s.cardsPerished],['Rot consumed',s.rotConsumed],['Combats',s.combats],['Turns',s.turns],['Damage taken',s.damageTaken]].map(x=>`<div class="stat"><b>${x[1]}</b>${x[0]}</div>`).join('')}</div><button class="btn primary" data-action="new">New run</button> <button class="btn" data-action="menu">Main menu</button></section></main>`;}
  function overlay(){const st=game.state,c=st.combat;if(c?.pendingChoice){return `<div class="modal-backdrop"><section class="modal"><h2>Choose an effect</h2><div class="choice-grid">${c.pendingChoice.options.map((o,i)=>`<button class="choice" data-action="option" data-id="${i}"><h3>${esc(o.label)}</h3></button>`).join('')}</div><button class="btn ghost" data-action="cancel">Cancel</button></section></div>`;}
    if(!st.overlay)return '';if(st.overlay==='settings')return settingsOverlay();if(st.overlay==='how')return howOverlay();if(st.overlay==='deck')return deckOverlay();if(st.overlay==='debug')return debugOverlay();if(st.overlay==='tutorialDone')return `<div class="modal-backdrop"><section class="modal"><button class="close" data-action="close">×</button><h2>Prologue complete</h2><p>You have aged, ripened, lost, consumed, and chosen. The Orchard Verge is ready.</p><button class="btn primary" data-action="new">Begin a full run</button></section></div>`;return '';}
  function settingsOverlay(){const s=game.settings;return `<div class="modal-backdrop"><section class="modal"><button class="close" data-action="close">×</button><h2>Settings</h2><div class="settings-grid"><label class="setting"><span><b>Text size</b><br><small>Scales UI text and controls.</small></span><input data-setting="textSize" type="range" min=".9" max="1.25" step=".05" value="${s.textSize}"></label><label class="setting"><span><b>Sound</b><br><small>Music and material cues.</small></span><input data-setting="volume" type="range" min="0" max="1" step=".05" value="${s.volume}"></label><label class="setting"><span><b>Reduced motion</b><br><small>Removes card pulses and travel.</small></span><input data-setting="reducedMotion" type="checkbox" ${s.reducedMotion?'checked':''}></label><label class="setting"><span><b>Hold to confirm perish</b><br><small>Hold End Turn for 0.7 seconds when a card will perish.</small></span><input data-setting="holdConfirm" type="checkbox" ${s.holdConfirm?'checked':''}></label><label class="setting"><span><b>Extended intents</b><br><small>Keep arithmetic visible in enemy labels.</small></span><input data-setting="extendedIntents" type="checkbox" ${s.extendedIntents?'checked':''}></label></div></section></div>`;}
  function howOverlay(){return `<div class="modal-backdrop"><section class="modal"><button class="close" data-action="close">×</button><h2>How to play</h2><div class="how-grid"><section><h3>Use it before you lose it</h3><p>Spend 3 Vigor each turn. Unplayed cards remain in hand. At end of turn, older perishable cards lose one pip. Cards drawn this turn cannot perish from ordinary aging.</p></section><section><h3>Fresh → Ripe → Rot</h3><p>Ripe is half Shelf Life or less. Some cards become stronger. At 0, a card becomes generic Rot. Rot clears after combat, but consumer cards can turn it into damage, Guard, or healing.</p></section><section><h3>Preserve and Seal</h3><p>Preserve restores pips up to printed maximum. Seal prevents the next ordinary aging step. Bruise removes pips directly.</p></section><section><h3>Status glossary</h3><p><b>Tender:</b> next attack takes +50%. <b>Mold:</b> Bruise a random card at turn end. <b>Sated:</b> the next card costs 1 more.</p></section><section><h3>Controls</h3><p>Click a card to play. Click an enemy to target it. Keys 1–8 play cards, E ends the turn, D opens the deck, Esc closes a window, and &#96; opens debug tools.</p></section><section><h3>End-turn order</h3><p>Cards age → perish triggers resolve → Mold resolves → enemy intents resolve left to right. Hover End Turn to highlight every card that will perish.</p></section></div></section></div>`;}
  function deckOverlay(){const r=game.state.run,defs=r.deck.map(x=>S.cardById[x.id]),per=defs.filter(x=>x.shelf!=null),avg=per.length?(per.reduce((n,x)=>n+x.shelf,0)/per.length).toFixed(1):'—',pres=defs.filter(x=>/Preserve|Seal/i.test(x.text)).length,rot=defs.filter(x=>/Consume/i.test(x.text)).length;return `<div class="modal-backdrop"><section class="modal"><button class="close" data-action="close">×</button><h2>Supply ledger</h2><div class="summary"><span><b>${r.deck.length}</b> cards</span><span><b>${avg}</b> average Shelf Life</span><span><b>${pres}</b> preservation sources</span><span><b>${rot}</b> Rot consumers</span></div><div class="sort-row">Sort <button class="btn ghost" data-action="sort" data-id="cost">Cost</button><button class="btn ghost" data-action="sort" data-id="shelf">Shelf Life</button><button class="btn ghost" data-action="sort" data-id="type">Type</button></div><div class="deck-list">${deckRows('noop')}</div></section></div>`;}
  function debugOverlay(){return `<div class="modal-backdrop"><section class="modal"><button class="close" data-action="close">×</button><h2>Debug pantry</h2><p>Add any card, start any encounter, grant any relic, or open any event. Press <b>&#96;</b> to close.</p><div class="debug-grid"><div><h3>Cards</h3><div class="debug-list">${S.cards.map(c=>`<button class="btn ghost" data-action="debug-card" data-id="${c.id}">${esc(c.name)}</button>`).join('')}</div></div><div><h3>Enemies</h3><div class="debug-list">${S.enemies.map(e=>`<button class="btn ghost" data-action="debug-fight" data-id="${e.id}">${esc(e.name)}</button>`).join('')}</div></div><div><h3>Relics & events</h3><div class="debug-list">${S.relics.map(r=>`<button class="btn ghost" data-action="debug-relic" data-id="${r.id}">${esc(r.name)}</button>`).join('')}${S.events.map(e=>`<button class="btn ghost" data-action="debug-event" data-id="${e.id}">Event: ${esc(e.name)}</button>`).join('')}</div></div></div></section></div>`;}
  function render(){document.documentElement.style.setProperty('--ui-scale',game.settings.textSize);document.body.classList.toggle('reduced-motion',game.settings.reducedMotion);const s=game.state;let view=s.screen==='menu'?menu():s.screen==='map'?map():s.screen==='combat'?combat():s.screen==='reward'?reward():s.screen==='kitchen'?kitchen():s.screen==='camp'?camp():s.screen==='market'?market():s.screen==='event'?event():s.screen==='tutorialReward'?tutorialReward():s.screen==='victory'?runEnd(true):s.screen==='defeat'?runEnd(false):menu();root.innerHTML=view+overlay()+(s.toast?`<div class="toast">${esc(s.toast)}</div>`:'');const latest=s.combat?.log?.[0];if(latest){const sig=latest.turn+latest.kind+latest.text;if(sig!==seenLog){seenLog=sig;audio.cue(latest.kind);}}}

  root.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=el.dataset.id;try{
    if(a==='new'||a==='new-seed'){const input=document.getElementById('seed-input');game.newRun(input?.value||Date.now());}
    else if(a==='continue')game.continue();else if(a==='tutorial')game.newRun('PROLOGUE',true);else if(a==='how'){game.state.overlay='how';game.emit(false);}else if(a==='settings')game.openSettings();else if(a==='close')game.closeOverlay();else if(a==='menu'){game.state.overlay=null;game.state.screen='menu';game.onChange(game.state);}else if(a==='deck')game.openDeck();else if(a==='debug'){game.state.overlay='debug';game.emit(false);}else if(a==='node')game.chooseNode(Number(id));else if(a==='enemy')game.selectEnemy(Number(id));else if(a==='card'){const c=game.state.combat;if(c?.pendingPlay)game.targetCard(Number(id));else game.playCard(Number(id));}else if(a==='cancel')game.cancelPending();else if(a==='option')game.chooseOption(Number(id));else if(a==='end'){const pending=game.state.combat?.hand.filter(willPerish).length;if(!game.settings.holdConfirm||!pending)game.endTurn();}
    else if(a==='reward')game.takeReward(game.state.run.deck.find(x=>x.uid===id)?.id||id);else if(a==='reward-coin')game.takeReward(null);else if(a==='reward-skip')game.advanceMap();else if(a==='upgrade')game.kitchenUpgrade(Number(id));else if(a==='camp-heal')game.campHeal();else if(a==='camp-upgrade')game.campUpgrade();else if(a==='buy-card')game.buyCard(id);else if(a==='buy-relic')game.buyRelic(id);else if(a==='remove')game.removeCard(Number(id));else if(a==='leave-market')game.leaveMarket();else if(a==='event-choice')game.chooseEvent(Number(id));else if(a==='tutorial-finish')game.finishTutorialChoice(id);else if(a==='sort'){uiSort=id;game.emit(false);}else if(a==='debug-card')game.debugAddCard(id);else if(a==='debug-fight')game.debugFight(id);else if(a==='debug-relic')game.debugRelic(id);else if(a==='debug-event')game.debugEvent(id);
    setTimeout(()=>{try{audio.ensure()}catch(error){/* Sound is optional; input must never be. */}},0);
    }catch(error){console.error(error);game.notify(`Input error: ${error.message}`);}
  });
  root.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-action=end]');if(!b||!game.settings.holdConfirm||!game.state.combat?.hand.filter(willPerish).length)return;b.classList.add('holding');endTimer=setTimeout(()=>{endTimer=null;game.endTurn();},720);});
  ['pointerup','pointerleave','pointercancel'].forEach(type=>root.addEventListener(type,e=>{if(endTimer){clearTimeout(endTimer);endTimer=null;}e.target.closest?.('[data-action=end]')?.classList.remove('holding');}));
  root.addEventListener('input',e=>{const key=e.target.dataset.setting;if(!key)return;const value=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);game.updateSettings({[key]:value});audio.volume();});
  window.addEventListener('keydown',e=>{if(e.key==='Escape'){game.closeOverlay();game.cancelPending();}if(e.key==='`'&&game.state.run){game.state.overlay=game.state.overlay==='debug'?null:'debug';game.emit(false);}if(game.state.screen==='combat'&&!game.state.overlay){if(/^[1-8]$/.test(e.key)){const card=game.state.combat.hand[Number(e.key)-1];if(card)game.playCard(card.uid);}if(e.key.toLowerCase()==='e')game.endTurn();if(e.key.toLowerCase()==='d')game.openDeck();}});
  if(new URLSearchParams(location.search).get('debug')==='combat'){
    game.newRun('SHOWCASE');game.startCombat(['market_hound','mold_finch']);
    const wanted=['red_knife','folded_leaf','summer_peach','hardtack','scrape_board'];
    game.state.combat.hand=wanted.map(id=>game.makeCombatCard({uid:game.uid++,id,upgraded:false,shelfBonus:0}));
    game.state.combat.turn=3;game.state.combat.vigor=3;game.state.combat.guard=7;game.state.combat.rot=2;game.state.run.hp=58;game.state.run.coin=14;
    game.state.combat.hand.forEach((card,i)=>{card.drawnTurn=i===1?3:1;if(card.freshness!=null)card.freshness=Math.max(1,card.maxFreshness-(i===0?1:0));});
    game.state.combat.hand.find(x=>x.id==='scrape_board').freshness=1;game.emit(false);
  }else render();
})();
